# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: money-fixer-io 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "money-fixer-io"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kaspernj"]
  s.date = "2016-10-01"
  s.description = "fixer.io support for money"
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/money-fixer-io.rb",
    "money-fixer-io.gemspec",
    "shippable.yml",
    "spec/money-fixer-io_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/money-fixer-io"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "fixer.io support for money"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 3.5.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["= 2.1.1"])
      s.add_development_dependency(%q<money>, ["= 6.7.1"])
      s.add_development_dependency(%q<rubocop>, ["= 0.43.0"])
    else
      s.add_dependency(%q<rspec>, ["= 3.5.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["= 2.1.1"])
      s.add_dependency(%q<money>, ["= 6.7.1"])
      s.add_dependency(%q<rubocop>, ["= 0.43.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 3.5.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["= 2.1.1"])
    s.add_dependency(%q<money>, ["= 6.7.1"])
    s.add_dependency(%q<rubocop>, ["= 0.43.0"])
  end
end

